# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wwdcdownloader 20.18.1 ruby lib

Gem::Specification.new do |s|
  s.name = "wwdcdownloader".freeze
  s.version = "20.18.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Johannes Fahrenkrug".freeze]
  s.date = "2018-06-06"
  s.description = "At each year's WWDC, Apple releases great sample projects. Unfortunately it is very tedious to manually download all these treasures through your browser. WWDC-Downloader solves this problem for you!".freeze
  s.email = "johannes@springenwerk.com".freeze
  s.executables = ["wwdcdownloader".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "bin/wwdcdownloader",
    "lib/wwdcdownloader.rb",
    "wwdcdownloader.gemspec"
  ]
  s.homepage = "https://github.com/jfahrenkrug/WWDC-Downloader".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.5.2".freeze
  s.summary = "A small tool to download all the sample code of Apple's latest WWDC developer conference".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>.freeze, ["~> 1.8.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.16.2"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
    else
      s.add_dependency(%q<json>.freeze, ["~> 1.8.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.16.2"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
    end
  else
    s.add_dependency(%q<json>.freeze, ["~> 1.8.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.16.2"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
  end
end

